- name: Ensure SVN packages are installed.
  yum: "name={{ item }} state=installed"
  with_items:
    - httpd
    - mod_dav_svn
    - subversion
    - python-passlib

- name: create systemd service
  template:
    dest: /usr/lib/systemd/system/svnserve.service
    src: systemd.j2
  notify:
    - enable svnserve

